# Generated by Django 5.2.6 on 2025-09-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('current_density', models.IntegerField(default=0)),
                ('accident_detected', models.BooleanField(default=False)),
            ],
        ),
    ]
